services:
  mongo:
    image: mongo:6
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: minijuniando

  mongo-express:
    image: mongo-express
    ports:
     - "8081:8081"
    environment:
      ME_CONFIG_ADMINUSERNAME: root
      ME_CONFIG_ADMINPASSWORD: minijuniando
      ME_CONFIG_MONGODB_URL: "mongodb://root:minijuniando@mongo:27017/"
