services:
  mongo:
    build:
      context: ./docker/mongo
      dockerfile: Dockerfile
    ports:
      - "27017:27017"
    volumes:
      - ./docker/mongo-init-rset.sh:/docker-entrypoint-initdb.d/mongo-init-rset.sh
    command: ["mongod", "--replSet", "rs0", "--bind_ip_all"]
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "rs.status().ok"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s

  mongo-express:
    image: mongo-express
    depends_on:
      mongo:
        condition: service_healthy
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_ENABLE_ADMIN: true
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: minijuniando
      ME_CONFIG_MONGODB_AUTH_DATABASE: admin
      ME_CONFIG_MONGODB_REPLICASET: rs0
